// Generated by Wrangler on Fri Apr 12 2024 16:31:47 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database
}
